image: Visual Studio 2019
environment:
  AOM_LAST_TAG: "v1.0.0"
  aom_options: " -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=OFF -DENABLE_TESTDATA=OFF -DENABLE_DOCS=OFF -DENABLE_TOOLS=OFF "

  matrix:
#  - arch: ARM64
#    aom_extra_options: " -DAOM_TARGET_CPU=arm64 "
  - arch: x64
    aom_extra_options: " -DENABLE_NASM=ON "

branches:
  only:
  - master

skip_tags: true
clone_depth: 1

configuration: Release

init:
# Clone last AOM code (Is different from the appveyor git clone)
- git clone -b master https://aomedia.googlesource.com/aom c:\projects\aom_src

# Change appveyor to know last aom commit
- ps: |
     cd c:\projects\aom_src
     $gitData = ConvertFrom-StringData (git log -1 --format=format:"commitId=%H%nmessage=%s%ncommitted=%aD" | out-string)
     if ($gitData['message'] -eq "") { $gitData['message'] = "No commit message available for $($gitData['commitid'])" }
     Update-AppveyorBuild @gitData

# Create aom version
- ps: |
     $count = (& git rev-list "$env:AOM_LAST_TAG.." --count).Trim()
     $commit = (& git log -1 --format=format:"%h").Trim()
     $version = "$env:AOM_LAST_TAG-$count-g$commit"
     echo $version
     Update-AppveyorBuild -Version $version
     $version >> ".\$version.txt"
     Push-AppveyorArtifact "$version.txt"

# Install nasm
install:
 - if %arch% == x64 cinst nasm & set PATH=%PROGRAMFILES%\NASM;%PATH%

# Prepare Build with cmake
before_build:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir cmake_build
    cd cmake_build
    cmake --version
    cmake c:\projects\aom_src %aom_options% %aom_extra_options% -A %arch%

# Build aom with Visual Studio 2019
build:
  project: C:\projects\build-aom\cmake_build\AOM.sln
  verbosity: minimal
  parallel: true

# Push files to artifacts
after_build:
- appveyor AddMessage "Finish build" -Category Information
- cd %APPVEYOR_BUILD_FOLDER%\cmake_build\Release\
- appveyor PushArtifact aomenc.exe
- appveyor PushArtifact aomdec.exe
- appveyor AddMessage "Finish upload" -Category Information
